name = "simple-chat"
main = "worker.ts"
compatibility_date = "2025-12-03"

[build]
command = ""

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]   # 免费计划必填这个
